#!/usr/bin/env python3
"""Apply the immutable protocol gates and render its measurement reports."""
from pathlib import Path
import json,sys
import numpy as np
import pandas as pd
from grappling_identity_separation_v1 import OUT,BASE,SEED,sha,js,R

def table(d,cols=None):
 d=d[cols] if cols else d
 def fmt(v):
  if pd.isna(v):return 'NA'
  if isinstance(v,(float,np.floating)):return f'{v:.3f}'
  return str(v).replace('|','/').replace('\n',' ')
 lines=['| '+' | '.join(d.columns)+' |','| '+' | '.join(['---']*len(d.columns))+' |']
 lines += ['| '+' | '.join(fmt(v) for v in row)+' |' for row in d.itertuples(index=False,name=None)]
 return '\n'.join(lines)+'\n'
def write(n,title,text):
 (OUT/(n+'.md')).write_text('# '+title+'\n\n'+text.rstrip()+'\n')
def main():
 import secondary_grappling_identity_separation_v1 as secondary
 secondary.main()
 extra=pd.read_csv(OUT/'support_secondary_separation.csv')
 rep=pd.read_csv(OUT/'replication.csv');sup=pd.read_csv(OUT/'support.csv');sep=pd.read_csv(OUT/'separation.csv');reg=pd.read_csv(OUT/'region_replication.csv');de=pd.read_csv(OUT/'division_era.csv');br=pd.read_csv(OUT/'boundary_redundancy.csv');dist=pd.read_csv(OUT/'cell_distributions.csv');ss=pd.read_csv(OUT/'sensitivity.csv')
 def rr(y,k,screen):return rep[(rep.year==y)&(rep.metric==k)&(rep.screen==screen)].iloc[0]
 def both(y,screen,n,r,low=None):
  return all((lambda x:x.n>=n and x.spearman>=r and (low is None or x.ci_low>low))(rr(y,k,screen)) for k in ['control','submission'])
 same=sep[(sep.year==2026)&sep.scope.str.endswith('_residual')];red=bool(len(same)==2 and same.spearman.abs().lt(.8).all() and br[br.year==2026].spearman.abs().lt(.8).all())
 rg=reg[(reg.year==2026)&reg.region.isin([1,2])]
 division=de[(de.year==2026)&de.scope.eq('division')];dd=division.pivot(index='group',columns='metric',values='spearman');nn=division.pivot(index='group',columns='metric',values='n');passed_div=int(((dd[['control','submission']]>=.2).all(axis=1)&(nn[['control','submission']]>=25).all(axis=1)).sum())
 era=de[(de.year==2026)&de.scope.eq('era')];loo=de[(de.year==2026)&de.scope.eq('leave_division_out')]
 early=sup[sup.scope.eq('scoring_prefight')&sup.division.eq('ALL')]
 gates={
  'G1_repeatability':both(2026,'primary',100,.3,.15) and both(2026,'same_access',25,.25,0),
  'G2_nonredundancy':red,
  'G3_regions_and_replication':bool(len(rg)==2 and rg.n.ge(25).all() and rg.share.ge(.05).all() and rg.excess.ge(.05).all() and rg.ci_low.gt(0).all()),
  'G4_support_and_chronology':both(2026,'same_access_strict',50,.25) and bool(len(early)==9 and early.both_share.ge(.5).all()) and both(2018,'primary',50,.25),
  'G5_division_and_era':passed_div>=4 and bool(len(loo)>0 and loo.spearman.ge(.25).all()) and bool(era.group.nunique()==2 and era.n.ge(50).all() and era.spearman.ge(.25).all())}
 partial=both(2026,'same_access',50,.2,0) and red and bool(len(rg)==2 and rg.n.ge(10).all())
 conclusion='A — GRAPPLING IDENTITY SEPARATION SUPPORTED' if all(gates.values()) else ('B — PARTIAL SEPARATION SUPPORTED' if partial else 'C — IDENTITY SEPARATION NOT SUPPORTED')
 limitation='The only failed A gate is discordant-region replication: high-control/low-SUB retention is 22.4% versus 24.1% stratum-matched prevalence (excess -1.7 percentage points; 95% CI -10.1 to +7.1). Low-control/high-SUB retention is 28.8% versus 22.2% (excess +6.6 points; CI -3.2 to +16.7). The respective 67 and 52 fighters establish populated descriptive regions, but neither supplies a positive lower bound for excess retention. These regions are not reliable grinder/submission-seeker identities. Continuous dimensions remain supportable, with uncertainty and missingness.'
 next_milestone='UFC_EDGE_GROUND_IDENTITY_SUPPORT_AWARE_REPRESENTATION_CONTRACT_V1' if conclusion[0] in ['A','B'] else 'UFC_EDGE_DECISION_CONTROL_MEASUREMENT_SUPPORT_REDESIGN_CONTRACT_V1'
 js(OUT/'GATE_DECISIONS.json',{'conclusion':conclusion,'gates':{k:bool(v) for k,v in gates.items()},'partial_gate':bool(partial),'divisions_passing':passed_div,'next_milestone':next_milestone,'protocol_sha256':sha(OUT/'GRAPPLING_IDENTITY_EXPERIMENT_PROTOCOL.md'),'protocol_freeze_commit':'8be3a32181ec90471902482161826301ffb74110'})
 common='\n\nHistories use strict event-date priors with target and same-date exclusion, sealed through 2026-08-15. Continuous behavioral rates do not establish intention, top control, true ground exposure or causal effects. This is developmental historical evidence; repeated fighters and nested boundaries are dependent. No predictive model or prospective confirmation outcomes were used.\n'
 write('ACCESS_MATCHING_SPECIFICATION','Frozen access matching', 'ACCESS = jointly observed TD attempts / governed total elapsed minutes. Three complete measured bouts and >=15 minutes screen broad support. PR160 used per15; division by 15 only changes units. Boundary average-rank quartiles use supported training-fighter snapshots. Block cuts are learned from first-three histories only and carried unchanged to next-three histories. Same-quartile pairs are primary; crossing strata are retained in block_states.csv.gz. Quartiles permit residual access variation and do not match opponents, TD completion, or actual ground opportunity.\n\nSee access_edges.csv, separation.csv and region_replication.csv. Within-stratum rank centering is descriptive removal of broad access strata; no outcome model is fitted. Regions use fixed first-side medians with equality in low. They are hypothesis checks, not four natural fighter classes.'+common)
 write('CONTROL_IDENTITY_MEASUREMENT','Decision-only control identity','CONTROL = control seconds / (60 × jointly observed decision elapsed minutes). Prior DECISION fights only, including decisions regardless of winner. Preserve control_num, control_den_min, control_bouts, control_missing_bouts and prior_decisions. >=1 measured decision and >=15 decision minutes is primary; >=2 decisions is stricter. In block replication, all decisions in each fixed three-bout block must have complete measurement; missing decisions are never replaced by later ones. No prior decision means missing raw control.\n\nAll-history control is the fixed selection comparator:\n\n'+table(ss[ss.comparison.eq('decision_vs_all_control')])+ '\nDecision conditioning reduces terminal truncation but selects opponent/durability/style environments. High agreement with all-history share does not prove decision-only superiority. Transparent 900-second prior exposure is a descriptive sensitivity; seconds are correlated duration, not independent Bernoulli trials.'+common)
 write('SUBMISSION_IDENTITY_MEASUREMENT','Submission-seeking identity','SUBMISSION = SUB attempts / jointly observed governed elapsed minutes, all historical complete measured bouts. >=3 matched bouts and >=15 minutes is broad support; block replication requires all three bouts measured. Recorded zero attempts with observed exposure is meaningful zero activity; absence of history is missing. No SUB-win outcome term, attempt quality, conversion or grounded denominator is introduced.\n\nThe fixed 15-minute prior-exposure sensitivity is within-division, strict-prior and excludes the focal fighter. It is descriptive; it does not turn unsupported states into usable identities.'+common)
 write('GNP_IDENTITY_MEASUREMENT','Secondary ground-striking tendency','GNP = significant ground-strike attempts / jointly observed total elapsed minutes, >=3 measured bouts and >=15 minutes. PR160 deferred primary GnP expansion; this experiment measures its existing total-time tendency without promoting a third identity. GnP success never affects classification.\n\n'+table(rep[(rep.year.isin([2018,2026]))&rep.metric.eq('gnp')&rep.screen.isin(['primary','same_access'])])+ '\nWithin-access dependence on the primary dimensions (secondary only):\n\n'+table(extra[extra.year.eq(2026)&extra.screen.eq('primary')&extra.representation.eq('raw')&extra.x.eq('gnp')])+ '\nGnP is not promoted merely because it has low redundancy: repeatability is still required. Ground activity can follow knockdowns, bottom exchanges or opponent takedowns. It omits nonsignificant punches and has no ground-KO attribution. No genuine ground-minute rate is claimed.'+common)
 write('NONOVERLAPPING_REPLICATION_RESULTS','Disjoint-history replication',table(rep[rep.screen.isin(['primary','same_access','same_access_strict'])&rep.metric.isin(['control','submission'])])+ '\nFirst three versus next three chronological UFC bouts; no qualifying-decision replacement. Each fighter is one observation per year. 2,000 seeded fighter bootstrap draws; first-block median direction agreement excludes ties. N<25 coefficients and intervals are missing. Ordinary Pearson appears beside rank persistence. The first-block/next-block sample selects six-bout survivors and is not a prospective replication. Requiring the same access quartile in both blocks selects stable-access careers and can strengthen correlation; its 266 joint fighters do not represent every fighter.\n\n'+table(pd.DataFrame([{'gate':k,'pass':v} for k,v in gates.items()]))+common)
 write('COMPARABLE_ACCESS_SEPARATION_RESULTS','Comparable-access separation','Boundary and block tables preserve every stratum; primary first/next residual rank dependence:\n\n'+table(sep[sep.scope.str.endswith('_residual')])+ '\n2026 discordant-region replication:\n\n'+table(rg)+ '\nRegion coding: 0 = low control/low SUB; 1 = low control/high SUB; 2 = high control/low SUB; 3 = high both. “High” is relative to prespecified first-block within-access median, not a natural class or a tactical-intent threshold. Bootstrap excess compares retention against the second-block marginal prevalence within each access stratum. Full boundary distributions and all four regions are in separation.csv, regions.csv and region_replication.csv.\n\nSupport/shrinkage sensitivity (2026):\n\n'+table(extra[extra.year.eq(2026)&extra.x.eq('control')])+ '\nThese descriptive sensitivities do not change the raw replication gates. Weak redundancy alone does not establish repeatable individual assignment. Both region retention and continuous repeatability must be considered.'+common)
 write('EARLY_FOLD_SUPPORT','Chronological support',table(early,['year','states','fighters','control_supported_share','submission_supported_share','both_share','gnp_supported_share','zero_history_share','median_prior_fights','median_prior_decisions','control_median_bouts'])+ '\nShares use every scoring fighter-side state, including debuts and unavailable dimensions. support.csv separately covers original training dates, January boundary unique training fighters, every division, matched denominators, activity numerators and low-support/missingness. Boundary cohorts must not be mistaken for support at the earlier training fights.\n\nA requires both identities supported for >=50% at every scoring year; stricter decision support and early replication are additional gates.'+common)
 write('DIVISION_ERA_STABILITY','Division and era stability',table(de[de.year.eq(2026)])+'\nEligible divisions meeting both rho>=0.20 with N>=25: '+str(passed_div)+'. Four are required for A. pre2015 versus 2015plus is fixed by first-block end date; it does not imply two independent careers. Leave-one-division-out prevents one division from supplying all pooled persistence. Bantamweight, Lightweight, Middleweight and Welterweight meet the frozen point-estimate gate; Bantamweight SUB uncertainty still crosses zero. Many divisions have fewer than 25 joint fighters and remain explicitly unsupported. Era persistence is positive in pre2015 (N=69) and 2015plus (N=197), so the pooled result is not solely modern. No division exclusion was chosen after results.'+common)
 write('B3_B5_IDENTITY_DISTRIBUTIONS','Frozen B3/B5 identity distributions',table(dist[dist.year.eq('ALL')&dist.representation.eq('raw')&dist.metric.isin(['control','submission','gnp'])])+ '\nUse all frozen scored cell bouts, both fighter sides. Membership IDs came from PR160 and were hash verified; no target method/outcome or saved probability was used in constructing this report. Compare supported continuous dispersion, not median-derived style labels. Cell-specific support differs and may explain apparent concentration. B3 has broad decision-control dispersion (IQR 0.162–0.461) and SUB activity dispersion (0.028–0.096 attempts/minute), consistent with mixed observed ground pathways. B5 has a narrower SUB IQR (0.031–0.089) but its median 0.061 is slightly below B3’s 0.065, and its SUB p10 is zero. Thus B5 is not uniformly high-SUB or more active than B3; both exceed the full scored median 0.025 among supported sides. B5 control median 0.234 is below B3 0.306. These descriptive results do not establish stable fighter archetypes. Neither cell identifies the attacking side or proves a causal mechanism. Annual/raw/pooled distributions and missingness are retained in cell_distributions.csv and cell_states.csv.gz.\n\nDecision-only control is sparser than all-history SUB, so heterogeneity among supported states cannot be generalized to unsupported cell sides.'+common)
 write('DIRECTIONAL_MATCHUP_READINESS','Directional matchup readiness','| Pathway | Available sides | Readiness limit |\n|---|---|---|\n| Control | A decision control/access; B measured control allowed and TD resistance | Generic CTRL includes clinch; no disengagement/escape opportunity or top retention |\n| Submission | A SUB activity; B attempts faced/prior SUB exposure | No threat quality, genuine opportunity or calibrated defense trials |\n| Ground strikes | A significant ground activity; B significant ground activity allowed | No top/bottom, damage or ground finish location; noisier tendency |\n\nFuture actor/opponent construction is conceptually feasible but is not implemented or approved here. Escape/disengagement remains unavailable, never filled with zero or a reversal proxy. A control × B control-allowed is an observed-behavior hypothesis, not a disengagement mechanism. Rates cannot directly become simulator transition hazards.'+common)
 write('SIMULATOR_IDENTITY_RECOMMENDATION','Simulator identity recommendation','**'+conclusion+'**\n\n'+limitation+'\n\n'+table(pd.DataFrame([{'criterion':k,'pass':v} for k,v in gates.items()]))+'\nRecommended next scientific milestone: **'+next_milestone+'**.\n\n'+ ('Freeze a support-aware continuous access/control/SUB representation contract with explicit unavailable/prior-dependent states, individual uncertainty and a prespecified repeatability check before any future predictive use. Retain raw counts, matched exposure, qualifying decisions and completeness flags. Do not claim broad fighter coverage, hard identities or simulator readiness from partial separation. No predictive challenger is authorized by this conclusion.' if conclusion[0] in ['A','B'] else 'Reconsider decision-only control support in a separately frozen measurement contract before any predictive challenger. Preserve this failed experiment unchanged; do not replace its gates or selector after seeing evidence.')+'\n\nGnP remains secondary descriptive activity and escape remains missing. The proposed ground identity is a noisy behavioral vector rather than full ground state, tactical intention, measured opportunity or calibrated transition probability.\n\nShrinkage sensitivity:\n\n'+table(ss[ss.year.eq(2026)])+'\nFixed population exposure reduces sparse-rate extremes; no tuned strength or fitted outcome model. Shared priors can inflate persistence, which is why raw values determine every replication gate. Unsupported/debut states remain unsupported even when a pooled estimate exists. Individual calibrated uncertainty still needs its own future contract.'+common)
 write('README','Frozen grappling identity separation V1','**'+conclusion+'**\n\nStarting main '+BASE+'. Protocol frozen at 8be3a32181ec90471902482161826301ffb74110 before new tables. Run offline with `python tools/audits/grappling_identity_separation_v1.py`, then `python tools/audits/report_grappling_identity_separation_v1.py` (also generates the secondary support table), then `python tools/audits/verify_grappling_identity_separation_v1.py --rerun`. Measurement tables can be regenerated into `--output-dir` and compared byte-for-byte. Source seal, memberships, scientific thresholds and restrictions are preserved.\n\nRead SIMULATOR_IDENTITY_RECOMMENDATION.md for gate decisions. No predictive model was trained; draft PR only.'+common)
 print(json.dumps({'conclusion':conclusion,'gates':gates,'next':next_milestone}))
if __name__=='__main__':main()
